### ISSUE TITLE
MipRobot.didReceiveRobotCommand is not fired

### ISSUE THREAD

**Issue by cybaker** [WowWeeLabs/MiP-Android-SDK#1]
For Android, using the latest Eclipse sample code of 26 August, there is no feedback from the robot when issuing commands such as readMipSensorWeightLevel() and readMipStatus(). From debugging the first line MipRobot.didReceiveRobotCommand, that method is never called, thus callbacks such as mipRobotDidReceiveWeightReading and mipRobotDidReceiveBatteryLevelReading are never fired. 

The robot accepts the commands for playing sound, changing chest LED colors, and driving without issue, so the connection is alive and working well. Just no callbacks.

**Comment by Cross22** [comment]
There is a BlueToothRobotPrivate class which has the callback handler in it. Unfortunately MipRobot is derived from BlueToothRobot instead, which has an empty method body for propertyChange() hence callbacks are not propagated. 
If the SDK was open-source this would be a 1 minute fix...

**Comment by dnocchi** [comment]
I have already sent two e-mails to apps@wowweelabs.com few weeks ago for this issue but still no answer from them ...

**Comment by cybaker** [comment]
Thanks Cross22 and dnocchi. I did more digging and found the same answer - I may modify the decompiled code on my own to enable this.

I've also got a Miposaur and would like to send commands across and see what the Miposaur's ball is transmitting. As a follower bot, the Miposaur is actually pretty good. It's also just wide enough to strap a small Android phone on the bottom (about 2.5in), which could allow the camera (with a mirror) to do facial recognition and send commands right to the bot, plus add a lot of computing power, allow for wireless charging, etc. Lots of ideas, so little time:)

**Comment by Cross22** [comment]
I have created a workaround in my demo project. Just copy the two files below into your app and use the MipRobotFinderFixed / MipRobotFixed classes. This also adds a basic handler for range detection...

https://github.com/Cross22/Miply/tree/master/app/src/main/java/com/wowwee/bluetoothrobotcontrollib/sdk

**Comment by hongkongkiwi** [comment]
Hi Guys, Thanks for the updates! We will look at getting this fixed next week.

I will discuss with our management about open sourcing the Android library, I think it could be beneficial to get the community's help in fixing bugs.

**Comment by ffchan** [comment]
The didReceiveRobotCommand and related problem have fix at commit c34a807cb19250c06bf96217982cd6ff54dbdb9c

Thanks
